// <auto-generated />
using AiHcmCms.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AiHcmCms.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20210627083149_MinhBakeryMigration")]
    partial class MinhBakeryMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AiHcmCms.Models.Cake", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<string>("Avatar")
                        .HasMaxLength(250);

                    b.Property<float>("Discount");

                    b.Property<int>("IdCategory");

                    b.Property<string>("Name")
                        .HasMaxLength(250);

                    b.Property<float>("Price");

                    b.HasKey("ID");

                    b.HasIndex("IdCategory");

                    b.ToTable("Cake");
                });

            modelBuilder.Entity("AiHcmCms.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(250);

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("AiHcmCms.Models.EndUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(250);

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasMaxLength(124);

                    b.Property<string>("Password")
                        .HasMaxLength(124);

                    b.Property<string>("Phone")
                        .HasMaxLength(15);

                    b.Property<string>("Username")
                        .HasMaxLength(124);

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("AiHcmCms.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(124);

                    b.Property<long>("CreatedDate");

                    b.Property<int>("IdCustomer");

                    b.Property<string>("ShippingAdress")
                        .HasMaxLength(250);

                    b.Property<float>("Total");

                    b.HasKey("Id");

                    b.HasIndex("IdCustomer");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("AiHcmCms.Models.OrderDetail", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(124);

                    b.Property<int>("Amount");

                    b.Property<string>("IdOrder")
                        .HasMaxLength(124);

                    b.Property<int>("IdProduct");

                    b.Property<float>("Price");

                    b.Property<float>("Total");

                    b.HasKey("Id");

                    b.HasIndex("IdOrder");

                    b.HasIndex("IdProduct");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("AiHcmCms.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Avatar")
                        .HasMaxLength(200);

                    b.Property<long>("CreatedDate");

                    b.Property<string>("Email")
                        .HasMaxLength(124);

                    b.Property<string>("FirstName")
                        .HasMaxLength(124);

                    b.Property<string>("LastName")
                        .HasMaxLength(124);

                    b.Property<string>("Password")
                        .HasMaxLength(124);

                    b.Property<string>("Phone")
                        .HasMaxLength(15);

                    b.Property<string>("Username")
                        .HasMaxLength(124);

                    b.HasKey("Id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("AiHcmCms.Models.Cake", b =>
                {
                    b.HasOne("AiHcmCms.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AiHcmCms.Models.Order", b =>
                {
                    b.HasOne("AiHcmCms.Models.EndUser", "Customer")
                        .WithMany()
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AiHcmCms.Models.OrderDetail", b =>
                {
                    b.HasOne("AiHcmCms.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("IdOrder");

                    b.HasOne("AiHcmCms.Models.Cake", "Cake")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
