/* USER CONSTANT */
export const STORE_CURRENT_USER = "STORE_CURRENT_USER";
export const CURRENT_USER_UPDATE = "CURRENT_USER_UPDATE";
export const CURRENT_USER_UPDATE_AVATAR = "CURRENT_USER_UPDATE_AVATAR";
export const RECEIVE_USERS = "RECEIVE_USERS";
export const REMOVE_USER = "REMOVE_USER";
export const USERS_DATA_SHOULD_FETCH = "USERS_DATA_SHOULD_FETCH";

/* NOTIFICATION CONSTANT */
export const RECEIVE_NOTIFICATIONS = "RECEIVE_NOTIFICATIONS";
export const MARK_NOTIFICATION = "MARK_NOTIFICATION";

/* LAYOUT CONSTANT */
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

/* DOCUMENT CONSTANT */
export const RECEIVE_DOCUMENTS = "RECEIVE_DOCUMENTS";
export const DOCUMENT_INSERT = "DOCUMENT_INSERT";
export const DOCUMENT_REMOVE = "DOCUMENT_REMOVE";

/* POST CONSTANT */
export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const UPDATE_POST = "UPDATE_POST";
export const CREATE_POST = "CREATE_POST";
export const DELETE_POST = "DELETE_POST";
export const REFRESH_POSTS = "REFRESH_POSTS";

/* PRODUCT CONSTANT */
export const RECEIVE_PRODUCT = "RECEIVE_PRODUCT";
// export const RECEIVE_PRODUCT_BYID = "RECEIVE_PRODUCT_BYID";
export const PRODUCTS_DATA_SHOULD_FETCH = "PRODUCTS_DATA_SHOULD_FETCH";
export const CURRENT_PRODUCT_UPDATE = "CURRENT_PRODUCT_UPDATE";
// export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
// export const RECEIVE_PRODUCT_CART = "RECEIVE_PRODUCT_CART";


/* CART CONSTANT */
export const STORE_IN_CART = "STORE_IN_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QTY_CART = "ADJUST_QTY_CART";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";



/* ORDER CONSTANT */
export const REICEVE_ORDER_BY_ID_CUS = "REICEVE_ORDER_BY_ID_CUS";
export const REICEVE_ORDER_BY_ID_ORD = "REICEVE_ORDER_BY_ID_ORD";
export const REICEVE_ALL_ORDER = "REICEVE_ALL_ORDER";
export const ORDERS_DATA_SHOULD_FETCH = "ORDERS_DATA_SHOULD_FETCH";
export const ADD_SHIPPING_ADDRESS = "ADD_SHIPPING_ADDRESS";